### ISSUE TITLE
As a user, I'd like to see a progress bar as the video is being played, so I can keep tracking the status of it

### ISSUE THREAD

**Issue by alternadiva** [alternadiva/Lyfta-Video-Player#3]
End user goal: See the actual status of the video on the progress bar

Acceptance Criteria:
- [x] Add progress bar
- [x] Set the range
- [x] Update the value as the video progressing
